# Generated by Django 4.0.2 on 2022-02-13 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_userprofile_alter_comments_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 10, 17, 54, 885415, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 10, 17, 54, 884414, tzinfo=utc)),
        ),
    ]
