# Generated by Django 4.0.2 on 2022-03-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_notification_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
